/**
 * @module C4ReadmeUtils.test
 * Unit tests for shared README staleness helpers.
 */
// Copyright (c) 2025, 2026 Jon Verrier

import { expect } from 'expect';
import { ETimeWindow, IDocGenOptions } from '../src/DocGenTypes';
import { isRollupOutputStale } from '../src/C4ReadmeUtils';

function makeOptions(overrides?: Partial<IDocGenOptions>): IDocGenOptions {
   return {
      rootDir: '/root',
      fileSpecs: ['*.ts'],
      timeWindow: ETimeWindow.kOneMonth,
      c4DiagramTypes: [],
      rollup: true,
      hasSubdirectorySources: true,
      jobStartedAt: new Date('2025-01-15'),
      ...overrides
   };
}

describe('C4ReadmeUtils.isRollupOutputStale', () => {
   it('returns true when root rollup is missing', () => {
      expect(isRollupOutputStale(null, ['<!-- Generated by StrongAIAutoDoc 20250101 -->\nchild'], [], makeOptions())).toBe(true);
   });

   it('returns true when a child README is newer than the root rollup', () => {
      const root = '<!-- Generated by StrongAIAutoDoc 20250110 -->\nroot';
      const child = '<!-- Generated by StrongAIAutoDoc 20250114 -->\nchild';
      expect(isRollupOutputStale(root, [child], [], makeOptions())).toBe(true);
   });

   it('returns true when a root module header is newer than the root rollup', () => {
      const root = '<!-- Generated by StrongAIAutoDoc 20250110 -->\nroot';
      expect(isRollupOutputStale(root, [], [new Date('2025-01-14')], makeOptions())).toBe(true);
   });

   it('returns true when a child README matches the root rollup date', () => {
      const root = '<!-- Generated by StrongAIAutoDoc 20250115 -->\nroot';
      const child = '<!-- Generated by StrongAIAutoDoc 20250115 -->\nchild';
      expect(isRollupOutputStale(root, [child], [], makeOptions())).toBe(true);
   });

   it('returns false when root rollup is newer than all inputs', () => {
      const root = '<!-- Generated by StrongAIAutoDoc 20250114 -->\nroot';
      const child = '<!-- Generated by StrongAIAutoDoc 20250110 -->\nchild';
      expect(isRollupOutputStale(root, [child], [new Date('2025-01-10')], makeOptions())).toBe(false);
   });
});
