/**
 * @module C4ReadmeUtils.test
 * Unit tests for shared README staleness helpers.
 */
// Copyright (c) 2025, 2026 Jon Verrier

import { expect } from 'expect';
import { EC4DiagramType, IDocGenOptions } from '../src/DocGenTypes';
import {
   isRollupOutputStale,
   validateC4OutputFilename,
   getC4OutputFilename
} from '../src/C4ReadmeUtils';
import { InvalidParameterError } from '@jonverrier/prompt-repository';
import { makeTestDocGenOptions } from './testDocGenOptions';

function makeOptions(overrides?: Partial<IDocGenOptions>): IDocGenOptions {
   return makeTestDocGenOptions({
      rollup: true,
      hasSubdirectorySources: true,
      ...overrides
   });
}

describe('C4ReadmeUtils.isRollupOutputStale', () => {
   it('returns true when root rollup is missing', () => {
      expect(isRollupOutputStale(null, ['<!-- Generated by StrongAIAutoDoc 20250101 -->\nchild'], [], makeOptions())).toBe(true);
   });

   it('returns true when a child README is newer than the root rollup', () => {
      const root = '<!-- Generated by StrongAIAutoDoc 20250110 -->\nroot';
      const child = '<!-- Generated by StrongAIAutoDoc 20250114 -->\nchild';
      expect(isRollupOutputStale(root, [child], [], makeOptions())).toBe(true);
   });

   it('returns true when a root module header is newer than the root rollup', () => {
      const root = '<!-- Generated by StrongAIAutoDoc 20250110 -->\nroot';
      expect(isRollupOutputStale(root, [], [new Date('2025-01-14')], makeOptions())).toBe(true);
   });

   it('returns true when a child README matches the root rollup date', () => {
      const root = '<!-- Generated by StrongAIAutoDoc 20250115 -->\nroot';
      const child = '<!-- Generated by StrongAIAutoDoc 20250115 -->\nchild';
      expect(isRollupOutputStale(root, [child], [], makeOptions())).toBe(true);
   });

   it('returns false when root rollup is newer than all inputs', () => {
      const root = '<!-- Generated by StrongAIAutoDoc 20250114 -->\nroot';
      const child = '<!-- Generated by StrongAIAutoDoc 20250110 -->\nchild';
      expect(isRollupOutputStale(root, [child], [new Date('2025-01-10')], makeOptions())).toBe(false);
   });
});

describe('C4ReadmeUtils.validateC4OutputFilename', () => {
   it('accepts a valid markdown basename', () => {
      expect(() => validateC4OutputFilename('ARCH.Component.md', '--component-file')).not.toThrow();
   });

   it('rejects README.md', () => {
      expect(() => validateC4OutputFilename('README.md', '--component-file')).toThrow(InvalidParameterError);
   });

   it('rejects path separators', () => {
      expect(() => validateC4OutputFilename('docs/out.md', '--context-file')).toThrow(InvalidParameterError);
   });

   it('rejects non-.md extensions', () => {
      expect(() => validateC4OutputFilename('diagram.txt', '--context-file')).toThrow(InvalidParameterError);
   });
});

describe('C4ReadmeUtils.getC4OutputFilename', () => {
   it('returns the configured filename for each diagram type', () => {
      const options = makeOptions({
         componentOutputFile: 'Custom.Component.md',
         contextOutputFile: 'Custom.Context.md'
      });
      expect(getC4OutputFilename(options, EC4DiagramType.kComponent)).toBe('Custom.Component.md');
      expect(getC4OutputFilename(options, EC4DiagramType.kContext)).toBe('Custom.Context.md');
   });
});
