/**
 * @module C4ReadmeUtils.test
 * Unit tests for shared README staleness helpers.
 */
// Copyright (c) 2025, 2026 Jon Verrier

import { expect } from 'expect';
import { EC4DiagramType, ETimeWindow, IDocGenOptions } from '../src/DocGenTypes';
import {
   buildReadmeDatestamp,
   extractReadmeGeneratedDate,
   isArtifactDateStale,
   isReadmeOutputStale,
   isRollupOutputStale,
   validateC4OutputFilename,
   getC4OutputFilename
} from '../src/C4ReadmeUtils';
import { InvalidParameterError } from '@jonverrier/prompt-repository';
import { makeTestDocGenOptions } from './testDocGenOptions';

function makeOptions(overrides?: Partial<IDocGenOptions>): IDocGenOptions {
   return makeTestDocGenOptions({
      rollup: true,
      hasSubdirectorySources: true,
      ...overrides
   });
}

describe('C4ReadmeUtils README datestamp contract', () => {
   it('buildReadmeDatestamp matches the documented HTML comment format', () => {
      const stamp = buildReadmeDatestamp(new Date('2025-03-25'));
      expect(stamp).toBe('<!-- Generated by StrongAIAutoDoc 20250325 -->\n\n');
   });

   it('extractReadmeGeneratedDate parses a valid datestamp', () => {
      const content = '<!-- Generated by StrongAIAutoDoc 20250110 -->\n\n# Diagram\n';
      const date = extractReadmeGeneratedDate(content);
      expect(date).not.toBeNull();
      expect(date!.getFullYear()).toBe(2025);
      expect(date!.getMonth()).toBe(0);
      expect(date!.getDate()).toBe(10);
   });

   it('extractReadmeGeneratedDate returns null when datestamp is absent', () => {
      expect(extractReadmeGeneratedDate('# Diagram only\n')).toBeNull();
   });

   it('extractReadmeGeneratedDate returns null for malformed datestamp', () => {
      expect(extractReadmeGeneratedDate('<!-- Generated by StrongAIAutoDoc BADDATE -->\n')).toBeNull();
   });

   describe('isArtifactDateStale', () => {
      it('returns true when artifact date is null', () => {
         expect(isArtifactDateStale(null, makeOptions())).toBe(true);
      });

      it('returns true when header is older than the configured time window', () => {
         const options = makeOptions({
            jobStartedAt: new Date('2025-01-15'),
            timeWindow: ETimeWindow.kOneWeek
         });
         expect(isArtifactDateStale(new Date('2025-01-01'), options)).toBe(true);
      });

      it('returns false when header is within the configured time window', () => {
         const options = makeOptions({
            jobStartedAt: new Date('2025-01-15'),
            timeWindow: ETimeWindow.kOneMonth
         });
         expect(isArtifactDateStale(new Date('2025-01-01'), options)).toBe(false);
      });
   });

   describe('isReadmeOutputStale', () => {
      it('returns true when content is null', () => {
         expect(isReadmeOutputStale(null, makeOptions())).toBe(true);
      });

      it('returns false when README datestamp is within the time window', () => {
         const content = '<!-- Generated by StrongAIAutoDoc 20250113 -->\n\n# Diagram';
         const options = makeOptions({
            jobStartedAt: new Date('2025-01-15'),
            timeWindow: ETimeWindow.kOneWeek
         });
         expect(isReadmeOutputStale(content, options)).toBe(false);
      });

      it('returns true when README datestamp is missing', () => {
         expect(isReadmeOutputStale('# No datestamp\n', makeOptions())).toBe(true);
      });
   });
});

describe('C4ReadmeUtils.isRollupOutputStale', () => {
   it('returns true when root rollup is missing', () => {
      expect(isRollupOutputStale(null, ['<!-- Generated by StrongAIAutoDoc 20250101 -->\nchild'], [], makeOptions())).toBe(true);
   });

   it('returns true when a child README is newer than the root rollup', () => {
      const root = '<!-- Generated by StrongAIAutoDoc 20250110 -->\nroot';
      const child = '<!-- Generated by StrongAIAutoDoc 20250114 -->\nchild';
      expect(isRollupOutputStale(root, [child], [], makeOptions())).toBe(true);
   });

   it('returns true when a root module header is newer than the root rollup', () => {
      const root = '<!-- Generated by StrongAIAutoDoc 20250110 -->\nroot';
      expect(isRollupOutputStale(root, [], [new Date('2025-01-14')], makeOptions())).toBe(true);
   });

   it('returns true when a child README matches the root rollup date', () => {
      const root = '<!-- Generated by StrongAIAutoDoc 20250115 -->\nroot';
      const child = '<!-- Generated by StrongAIAutoDoc 20250115 -->\nchild';
      expect(isRollupOutputStale(root, [child], [], makeOptions())).toBe(true);
   });

   it('returns false when root rollup is newer than all inputs', () => {
      const root = '<!-- Generated by StrongAIAutoDoc 20250114 -->\nroot';
      const child = '<!-- Generated by StrongAIAutoDoc 20250110 -->\nchild';
      expect(isRollupOutputStale(root, [child], [new Date('2025-01-10')], makeOptions())).toBe(false);
   });

   it('returns true when design file is newer than the root rollup', () => {
      const root = '<!-- Generated by StrongAIAutoDoc 20250110 -->\nroot';
      const child = '<!-- Generated by StrongAIAutoDoc 20250101 -->\nchild';
      expect(isRollupOutputStale(
         root,
         [child],
         [],
         makeOptions(),
         new Date('2025-01-14')
      )).toBe(true);
   });
});

describe('C4ReadmeUtils.validateC4OutputFilename', () => {
   it('accepts a valid markdown basename', () => {
      expect(() => validateC4OutputFilename('ARCH.Component.md', '--component-file')).not.toThrow();
   });

   it('rejects README.md', () => {
      expect(() => validateC4OutputFilename('README.md', '--component-file')).toThrow(InvalidParameterError);
   });

   it('rejects path separators', () => {
      expect(() => validateC4OutputFilename('docs/out.md', '--context-file')).toThrow(InvalidParameterError);
   });

   it('rejects non-.md extensions', () => {
      expect(() => validateC4OutputFilename('diagram.txt', '--context-file')).toThrow(InvalidParameterError);
   });
});

describe('C4ReadmeUtils.getC4OutputFilename', () => {
   it('returns the configured filename for each diagram type', () => {
      const options = makeOptions({
         componentOutputFile: 'Custom.Component.md',
         contextOutputFile: 'Custom.Context.md'
      });
      expect(getC4OutputFilename(options, EC4DiagramType.kComponent)).toBe('Custom.Component.md');
      expect(getC4OutputFilename(options, EC4DiagramType.kContext)).toBe('Custom.Context.md');
   });
});
