/**
 * @module DocumentationGenerator.e2e.test
 * End-to-end tests for the documentation generator. Uses real LLM calls and
 * real filesystem I/O. Copies fixture files to a temp directory, runs the full
 * pipeline, then asserts on the generated output files.
 *
 * These tests are skipped automatically if OPENAI_API_KEY is not set.
 * They are excluded from the coverage run (npm run cover) — run separately via
 * npm run test:e2e
 */
// Copyright (c) 2025, 2026 Jon Verrier

import { expect } from 'expect';
import * as fs from 'fs/promises';
import * as path from 'path';
import * as os from 'os';

import { DirectoryTreeTraverser, NodeDirectoryReader, MinimatchFileFilter } from '../src/DirectoryTreeTraverser';
import { VisitorFactory } from '../src/VisitorFactory';
import { IDocGenOptions, ETimeWindow, EC4DiagramType } from '../src/DocGenTypes';

// Fixture source files to copy into the temp directory
const FIXTURE_FILES = [
   'UserProfileComponent.tsx',
   'WorkoutService.ts',
   'ExerciseRepository.ts'
];
const FIXTURES_DIR = path.join(__dirname, 'fixtures');

// ---------------------------------------------------------------------------
// Suite
// ---------------------------------------------------------------------------

const describeE2e = process.env.OPENAI_API_KEY ? describe : describe.skip;

describeE2e('DocumentationGenerator e2e', () => {
   let tempDir: string;

   beforeEach(async () => {
      // Create a fresh temp directory and copy fixtures into it
      tempDir = await fs.mkdtemp(path.join(os.tmpdir(), 'strongai-docgen-'));
      for (const filename of FIXTURE_FILES) {
         const src  = path.join(FIXTURES_DIR, filename);
         const dest = path.join(tempDir, filename);
         await fs.copyFile(src, dest);
      }
   });

   afterEach(async () => {
      // Clean up temp directory
      try {
         await fs.rm(tempDir, { recursive: true, force: true });
      } catch {
         // Ignore cleanup errors
      }
   });

   // -------------------------------------------------------------------------
   it('generates header comments in all fixture files', async () => {
      const options: IDocGenOptions = {
         rootDir:      tempDir,
         fileSpecs:    ['*.ts', '*.tsx'],
         timeWindow:   ETimeWindow.kOneMonth,
         c4DiagramTypes: [],
         rollup: false,
         hasSubdirectorySources: false,
         jobStartedAt: new Date()
      };

      const visitors  = VisitorFactory.createAll(options);
      const traverser = new DirectoryTreeTraverser(visitors, new NodeDirectoryReader(), new MinimatchFileFilter());
      await traverser.traverse(options);

      // Each fixture should now contain the sentinel markers
      for (const filename of FIXTURE_FILES) {
         const outPath = path.join(tempDir, filename);
         const content = await fs.readFile(outPath, 'utf8');
         expect(content).toContain('===Start StrongAI Generated Comment');
         expect(content).toContain('===End StrongAI Generated Comment===');
      }
   });

   // -------------------------------------------------------------------------
   it('generates a C4 Component README with a Mermaid fence', async () => {
      const options: IDocGenOptions = {
         rootDir:        tempDir,
         fileSpecs:      ['*.ts', '*.tsx'],
         timeWindow:     ETimeWindow.kOneMonth,
         c4DiagramTypes: [EC4DiagramType.kComponent],
         rollup: false,
         hasSubdirectorySources: false,
         jobStartedAt:   new Date()
      };

      const visitors  = VisitorFactory.createAll(options);
      const traverser = new DirectoryTreeTraverser(visitors, new NodeDirectoryReader(), new MinimatchFileFilter());
      await traverser.traverse(options);

      const readmePath = path.join(tempDir, 'README.StrongAI.Component.md');
      const content    = await fs.readFile(readmePath, 'utf8');

      expect(content).toContain('<!-- Generated by StrongAIAutoDoc');
      expect(content).toContain('```mermaid');
   });

   // -------------------------------------------------------------------------
   it('generates both Component and Context READMEs when both flags are set', async () => {
      const options: IDocGenOptions = {
         rootDir:        tempDir,
         fileSpecs:      ['*.ts', '*.tsx'],
         timeWindow:     ETimeWindow.kOneMonth,
         c4DiagramTypes: [EC4DiagramType.kComponent, EC4DiagramType.kContext],
         rollup: false,
         hasSubdirectorySources: false,
         jobStartedAt:   new Date()
      };

      const visitors  = VisitorFactory.createAll(options);
      const traverser = new DirectoryTreeTraverser(visitors, new NodeDirectoryReader(), new MinimatchFileFilter());
      await traverser.traverse(options);

      const componentPath = path.join(tempDir, 'README.StrongAI.Component.md');
      const contextPath   = path.join(tempDir, 'README.StrongAI.Context.md');

      const componentContent = await fs.readFile(componentPath, 'utf8');
      const contextContent   = await fs.readFile(contextPath, 'utf8');

      expect(componentContent).toContain('```mermaid');
      expect(contextContent).toContain('```mermaid');
   });

   // -------------------------------------------------------------------------
   it('does not regenerate fresh files on a second run', async () => {
      const options: IDocGenOptions = {
         rootDir:        tempDir,
         fileSpecs:      ['*.ts', '*.tsx'],
         timeWindow:     ETimeWindow.kOneMonth,
         c4DiagramTypes: [EC4DiagramType.kComponent],
         rollup: false,
         hasSubdirectorySources: false,
         jobStartedAt:   new Date()
      };

      // First run
      const visitors1  = VisitorFactory.createAll(options);
      const traverser1 = new DirectoryTreeTraverser(visitors1, new NodeDirectoryReader(), new MinimatchFileFilter());
      await traverser1.traverse(options);

      // Capture mtimes after first run
      const mtimes: Record<string, number> = {};
      for (const filename of [...FIXTURE_FILES, 'README.StrongAI.Component.md']) {
         const p = path.join(tempDir, filename);
         try {
            const stat = await fs.stat(p);
            mtimes[filename] = stat.mtimeMs;
         } catch {
            // file may not exist yet
         }
      }

      // Small delay to ensure mtime would differ if files were rewritten
      await new Promise(resolve => setTimeout(resolve, 100));

      // Second run — everything should be fresh, nothing rewritten
      const visitors2  = VisitorFactory.createAll(options);
      const traverser2 = new DirectoryTreeTraverser(visitors2, new NodeDirectoryReader(), new MinimatchFileFilter());
      await traverser2.traverse(options);

      for (const [filename, originalMtime] of Object.entries(mtimes)) {
         const p = path.join(tempDir, filename);
         try {
            const stat = await fs.stat(p);
            expect(stat.mtimeMs).toBe(originalMtime);
         } catch {
            // If file doesn't exist, skip
         }
      }
   });
});
