/**
 * @module RollupC4Visitor.test
 * Unit tests for RollupC4Visitor rollup accumulation and finalize behaviour.
 */
// Copyright (c) 2025, 2026 Jon Verrier

import { expect } from 'expect';
import sinon from 'sinon';
import * as path from 'path';

import { RollupC4Visitor } from '../src/RollupC4Visitor';
import {
   EC4DiagramType,
   ETimeWindow,
   IDocGenOptions,
   IFileReader,
   IFileWriter
} from '../src/DocGenTypes';
import { IChatDriver, IPromptRepository, IPrompt } from '@jonverrier/prompt-repository';
import { c4ComponentRollupPromptId } from '../src/PromptIds';
import { makeTestDocGenOptions } from './testDocGenOptions';

const FAKE_ROLLUP = `Package overview.

\`\`\`mermaid
C4Component
   title Package
\`\`\`

Key areas.`;

const ROOT_HEADER = `// ===Start StrongAI Generated Comment (20250110)===
// CLI entry point.
// ===End StrongAI Generated Comment===`;

function makeOptions(overrides?: Partial<IDocGenOptions>): IDocGenOptions {
   return makeTestDocGenOptions({
      rootDir: path.resolve('/project/src'),
      timeWindow: ETimeWindow.kOneWeek,
      c4DiagramTypes: [EC4DiagramType.kComponent],
      rollup: true,
      hasSubdirectorySources: true,
      ...overrides
   });
}

function makePromptRepo(): IPromptRepository {
   const fakePrompt: IPrompt = {
      id: c4ComponentRollupPromptId,
      name: 'C4ComponentRollup',
      version: '1.0',
      systemPrompt: 'You are an architect.',
      userPrompt: '{subdirectorySummaries} {rootModuleHeaders} {designContext} {introWordCount} {detailWordCount}',
      userPromptParameters: [
         { name: 'subdirectorySummaries', description: '', type: 'kString', required: true },
         { name: 'rootModuleHeaders',     description: '', type: 'kString', required: true },
         { name: 'designContext',         description: '', type: 'kString', required: true },
         { name: 'introWordCount',        description: '', type: 'kNumber', required: true },
         { name: 'detailWordCount',       description: '', type: 'kNumber', required: true }
      ]
   };
   return {
      getPrompt:          sinon.stub().returns(fakePrompt),
      expandSystemPrompt: sinon.stub().returns('You are an architect.'),
      expandUserPrompt:   sinon.stub().returns('Roll up these docs.')
   } as unknown as IPromptRepository;
}

function makeChatDriver(returnValue = FAKE_ROLLUP): IChatDriver {
   return {
      getModelResponse:                        sinon.stub().resolves(returnValue),
      getStreamedModelResponse:                sinon.stub(),
      getModelResponseWithForcedTools:         sinon.stub(),
      getStreamedModelResponseWithForcedTools: sinon.stub(),
      getConstrainedModelResponse:             sinon.stub()
   } as unknown as IChatDriver;
}

describe('RollupC4Visitor', () => {
   afterEach(() => sinon.restore());

   it('stores root file paths but does not accumulate root README files', async () => {
      const rootDir = path.resolve('/project/src');
      const fileReader: IFileReader = {
         readFile: sinon.stub().rejects(new Error('missing'))
      };
      const fileWriter = { writeFile: sinon.stub().resolves() } as unknown as IFileWriter;
      const visitor = new RollupC4Visitor(
         fileReader,
         fileWriter,
         makeChatDriver(),
         makePromptRepo(),
         [EC4DiagramType.kComponent],
         ['*.ts']
      );

      await visitor.visit(rootDir, [path.join(rootDir, 'index.ts')], makeOptions());
      await visitor.finalize(makeOptions());

      expect((fileWriter.writeFile as sinon.SinonStub).callCount).toBe(0);
   });

   it('writes a rolled-up README at the scan root from subdirectory docs', async () => {
      const rootDir = path.resolve('/project/src');
      const childDir = path.join(rootDir, 'features');
      const childReadme = path.join(childDir, 'README.StrongAI.Component.md');
      const rootReadme = path.join(rootDir, 'README.StrongAI.Component.md');
      const fileReader: IFileReader = {
         readFile: sinon.stub().callsFake(async (filePath: string) => {
            if (filePath === childReadme) {
               return '<!-- Generated by StrongAIAutoDoc 20250101 -->\nChild component doc';
            }
            throw new Error(`Unexpected read: ${filePath}`);
         })
      };
      const fileWriter = { writeFile: sinon.stub().resolves() } as unknown as IFileWriter;
      const visitor = new RollupC4Visitor(
         fileReader,
         fileWriter,
         makeChatDriver(),
         makePromptRepo(),
         [EC4DiagramType.kComponent],
         ['*.ts']
      );

      await visitor.visit(childDir, [path.join(childDir, 'Feature.ts')], makeOptions());
      await visitor.finalize(makeOptions());

      expect((fileWriter.writeFile as sinon.SinonStub).callCount).toBe(1);
      const [writtenPath, writtenContent] = (fileWriter.writeFile as sinon.SinonStub).firstCall.args;
      expect(writtenPath).toBe(rootReadme);
      expect(writtenContent).toContain('<!-- Generated by StrongAIAutoDoc 20250115 -->');
      expect(writtenContent).toContain('Package overview.');
   });

   it('includes root module headers in the rollup prompt', async () => {
      const rootDir = path.resolve('/project/src');
      const childDir = path.join(rootDir, 'features');
      const childReadme = path.join(childDir, 'README.StrongAI.Component.md');
      const rootCli = path.join(rootDir, 'cli.ts');
      const fileReader: IFileReader = {
         readFile: sinon.stub().callsFake(async (filePath: string) => {
            if (filePath === childReadme) {
               return '<!-- Generated by StrongAIAutoDoc 20250101 -->\nChild component doc';
            }
            if (filePath === rootCli) {
               return `${ROOT_HEADER}\nexport {};\n`;
            }
            throw new Error(`Unexpected read: ${filePath}`);
         })
      };
      const promptRepo = makePromptRepo();
      const visitor = new RollupC4Visitor(
         fileReader,
         { writeFile: sinon.stub().resolves() } as unknown as IFileWriter,
         makeChatDriver(),
         promptRepo,
         [EC4DiagramType.kComponent],
         ['*.ts']
      );

      await visitor.visit(rootDir, [rootCli], makeOptions());
      await visitor.visit(childDir, [path.join(childDir, 'Feature.ts')], makeOptions());
      await visitor.finalize(makeOptions());

      const expandArgs = (promptRepo.expandUserPrompt as sinon.SinonStub).firstCall.args[1];
      expect(expandArgs.rootModuleHeaders).toContain('(root)');
      expect(expandArgs.rootModuleHeaders).toContain('cli.ts');
   });

   it('includes design context in the rollup prompt when Design.md exists', async () => {
      const rootDir = path.resolve('/project/src');
      const childDir = path.join(rootDir, 'features');
      const childReadme = path.join(childDir, 'README.StrongAI.Component.md');
      const designPath = path.join(path.dirname(rootDir), 'DESIGN.md');
      const fileReader: IFileReader = {
         readFile: sinon.stub().callsFake(async (filePath: string) => {
            if (filePath === childReadme) {
               return '<!-- Generated by StrongAIAutoDoc 20250101 -->\nChild component doc';
            }
            if (filePath === designPath) {
               return '# Design intent\nUse feature modules as boundaries.';
            }
            throw new Error(`Unexpected read: ${filePath}`);
         }),
         getFileModifiedTime: sinon.stub().callsFake(async (filePath: string) => {
            if (filePath === designPath) {
               return new Date('2025-01-12');
            }
            return null;
         })
      };
      const promptRepo = makePromptRepo();
      const fileWriter = { writeFile: sinon.stub().resolves() } as unknown as IFileWriter;
      const visitor = new RollupC4Visitor(
         fileReader,
         fileWriter,
         makeChatDriver(),
         promptRepo,
         [EC4DiagramType.kComponent],
         ['*.ts']
      );

      await visitor.visit(childDir, [path.join(childDir, 'Feature.ts')], makeOptions());
      await visitor.finalize(makeOptions());

      const expandArgs = (promptRepo.expandUserPrompt as sinon.SinonStub).firstCall.args[1];
      expect(expandArgs.designContext).toContain('DESIGN.md');
      expect(expandArgs.designContext).toContain('Use feature modules as boundaries.');
      expect((fileWriter.writeFile as sinon.SinonStub).callCount).toBe(1);
      expect((fileWriter.writeFile as sinon.SinonStub).firstCall.args[0]).not.toBe(designPath);
   });

   it('passes empty design context when no design file exists', async () => {
      const rootDir = path.resolve('/project/src');
      const childDir = path.join(rootDir, 'features');
      const childReadme = path.join(childDir, 'README.StrongAI.Component.md');
      const fileReader: IFileReader = {
         readFile: sinon.stub().callsFake(async (filePath: string) => {
            if (filePath === childReadme) {
               return '<!-- Generated by StrongAIAutoDoc 20250101 -->\nChild component doc';
            }
            throw new Error(`Unexpected read: ${filePath}`);
         })
      };
      const promptRepo = makePromptRepo();
      const visitor = new RollupC4Visitor(
         fileReader,
         { writeFile: sinon.stub().resolves() } as unknown as IFileWriter,
         makeChatDriver(),
         promptRepo,
         [EC4DiagramType.kComponent],
         ['*.ts']
      );

      await visitor.visit(childDir, [path.join(childDir, 'Feature.ts')], makeOptions());
      await visitor.finalize(makeOptions());

      const expandArgs = (promptRepo.expandUserPrompt as sinon.SinonStub).firstCall.args[1];
      expect(expandArgs.designContext).toBe('');
   });

   it('regenerates rollup when design file is newer than the root rollup', async () => {
      const rootDir = path.resolve('/project/src');
      const childDir = path.join(rootDir, 'features');
      const childReadme = path.join(childDir, 'README.StrongAI.Component.md');
      const rootReadme = path.join(rootDir, 'README.StrongAI.Component.md');
      const designPath = path.join(path.dirname(rootDir), 'DESIGN.md');
      const fileReader: IFileReader = {
         readFile: sinon.stub().callsFake(async (filePath: string) => {
            if (filePath === childReadme) {
               return '<!-- Generated by StrongAIAutoDoc 20250110 -->\nChild component doc';
            }
            if (filePath === rootReadme) {
               return '<!-- Generated by StrongAIAutoDoc 20250110 -->\nRoot rollup';
            }
            if (filePath === designPath) {
               return '# Updated design intent';
            }
            throw new Error(`Unexpected read: ${filePath}`);
         }),
         getFileModifiedTime: sinon.stub().callsFake(async (filePath: string) => {
            if (filePath === designPath) {
               return new Date('2025-01-14');
            }
            return null;
         })
      };
      const fileWriter = { writeFile: sinon.stub().resolves() } as unknown as IFileWriter;
      const visitor = new RollupC4Visitor(
         fileReader,
         fileWriter,
         makeChatDriver(),
         makePromptRepo(),
         [EC4DiagramType.kComponent],
         ['*.ts']
      );

      await visitor.visit(childDir, [path.join(childDir, 'Feature.ts')], makeOptions());
      await visitor.finalize(makeOptions({ jobStartedAt: new Date('2025-01-15') }));

      expect((fileWriter.writeFile as sinon.SinonStub).callCount).toBe(1);
   });

   it('regenerates rollup when a same-day per-directory root README exists', async () => {
      const rootDir = path.resolve('/project/src');
      const childDir = path.join(rootDir, 'features');
      const childReadme = path.join(childDir, 'README.StrongAI.Component.md');
      const rootReadme = path.join(rootDir, 'README.StrongAI.Component.md');
      const fileReader: IFileReader = {
         readFile: sinon.stub().callsFake(async (filePath: string) => {
            if (filePath === childReadme) {
               return '<!-- Generated by StrongAIAutoDoc 20250115 -->\nChild component doc';
            }
            if (filePath === rootReadme) {
               return '<!-- Generated by StrongAIAutoDoc 20250115 -->\nPer-directory root doc';
            }
            throw new Error(`Unexpected read: ${filePath}`);
         })
      };
      const fileWriter = { writeFile: sinon.stub().resolves() } as unknown as IFileWriter;
      const visitor = new RollupC4Visitor(
         fileReader,
         fileWriter,
         makeChatDriver(),
         makePromptRepo(),
         [EC4DiagramType.kComponent],
         ['*.ts']
      );

      await visitor.visit(childDir, [path.join(childDir, 'Feature.ts')], makeOptions());
      await visitor.finalize(makeOptions({ jobStartedAt: new Date('2025-01-15') }));

      expect((fileWriter.writeFile as sinon.SinonStub).callCount).toBe(1);
   });

   it('skips finalize writes when no subdirectory README files were found', async () => {
      const fileReader: IFileReader = {
         readFile: sinon.stub().rejects(new Error('missing'))
      };
      const fileWriter = { writeFile: sinon.stub().resolves() } as unknown as IFileWriter;
      const visitor = new RollupC4Visitor(
         fileReader,
         fileWriter,
         makeChatDriver(),
         makePromptRepo(),
         [EC4DiagramType.kComponent],
         ['*.ts']
      );

      await visitor.finalize(makeOptions());
      expect((fileWriter.writeFile as sinon.SinonStub).callCount).toBe(0);
   });

   it('scales word counts with input section count', () => {
      const visitor = new RollupC4Visitor(
         { readFile: sinon.stub() } as unknown as IFileReader,
         { writeFile: sinon.stub() } as unknown as IFileWriter,
         makeChatDriver(),
         makePromptRepo(),
         [EC4DiagramType.kComponent],
         ['*.ts']
      );

      const small = visitor.computeWordCounts(1);
      const large = visitor.computeWordCounts(9);
      expect(large.introWords + large.detailWords).toBeGreaterThan(small.introWords + small.detailWords);
   });
});
