/**
 * @module C4ReadmeUtils
 * Shared constants and helpers for StrongAI-generated C4 README markdown files.
 */
// Copyright (c) 2025, 2026 Jon Verrier

import { EC4DiagramType, ETimeWindow, IDocGenOptions } from './DocGenTypes';
import { InvalidParameterError } from '@jonverrier/prompt-repository';

/** Number of milliseconds per day, used for README staleness checks. */
export const MS_PER_DAY = 86400000;

/** Time-window durations in days. */
export const TIME_WINDOW_DAYS: Record<ETimeWindow, number> = {
   [ETimeWindow.kOneWeek]:  7,
   [ETimeWindow.kTwoWeeks]: 14,
   [ETimeWindow.kOneMonth]: 30
};

/** Default generated C4 markdown filenames (from the Strong AI tooling convention). */
export const DEFAULT_C4_OUTPUT_FILES: Record<EC4DiagramType, string> = {
   [EC4DiagramType.kComponent]: 'README.StrongAI.Component.md',
   [EC4DiagramType.kContext]:   'README.StrongAI.Context.md',
};

/** Filename that must never be used for generated C4 output. */
export const FORBIDDEN_PROJECT_README = 'README.md';

/**
 * Returns the output filename for a diagram type from parsed CLI options.
 * @param options - Parsed doc-gen options
 * @param diagramType - Component or Context diagram type
 * @returns Basename of the generated markdown file
 */
export function getC4OutputFilename(options: IDocGenOptions, diagramType: EC4DiagramType): string {
   switch (diagramType) {
      case EC4DiagramType.kComponent:
         return options.componentOutputFile;
      case EC4DiagramType.kContext:
         return options.contextOutputFile;
      default: {
         const _exhaustive: never = diagramType;
         return _exhaustive;
      }
   }
}

/**
 * Validates a user-supplied generated-doc filename.
 * @param filename - Proposed output basename
 * @param flagName - CLI flag name for error messages
 */
export function validateC4OutputFilename(filename: string, flagName: string): void {
   const trimmed = filename.trim();
   if (!trimmed) {
      throw new InvalidParameterError(`${flagName} requires a non-empty filename`);
   }
   if (trimmed.includes('/') || trimmed.includes('\\')) {
      throw new InvalidParameterError(`${flagName} must be a filename only, not a path: ${filename}`);
   }
   if (trimmed === FORBIDDEN_PROJECT_README) {
      throw new InvalidParameterError(`${flagName} must not be ${FORBIDDEN_PROJECT_README}; use a dedicated generated-doc name`);
   }
   if (!trimmed.toLowerCase().endsWith('.md')) {
      throw new InvalidParameterError(`${flagName} must end with .md: ${filename}`);
   }
}

/** Regex matching the datestamp embedded at the top of generated README files. */
export const README_DATESTAMP_RE = /^<!-- Generated by StrongAIAutoDoc (\d{8}) -->/m;

/** Prefix for the generated README datestamp comment. */
export const README_DATESTAMP_PREFIX = '<!-- Generated by StrongAIAutoDoc ';

/** Suffix for the generated README datestamp comment. */
export const README_DATESTAMP_SUFFIX = ' -->';

/**
 * Formats a Date as a compact YYYYMMDD string.
 * @param date - Date to format
 * @returns YYYYMMDD string
 */
export function formatDateYYYYMMDD(date: Date): string {
   const y = date.getFullYear();
   const m = String(date.getMonth() + 1).padStart(2, '0');
   const d = String(date.getDate()).padStart(2, '0');
   return `${y}${m}${d}`;
}

/**
 * Parses a YYYYMMDD string into a Date, returning null if malformed.
 * @param s - Date string to parse
 * @returns Parsed date or null
 */
export function parseDateYYYYMMDD(s: string): Date | null {
   if (!/^\d{8}$/.test(s)) return null;
   const year  = parseInt(s.substring(0, 4), 10);
   const month = parseInt(s.substring(4, 6), 10) - 1;
   const day   = parseInt(s.substring(6, 8), 10);
   const d = new Date(year, month, day);
   if (d.getFullYear() !== year || d.getMonth() !== month || d.getDate() !== day) {
      return null;
   }
   return d;
}

/**
 * Returns true if generated README content is absent or older than the configured time window.
 * @param existingContent - Current file content, if any
 * @param options - Doc-gen options including jobStartedAt and timeWindow
 * @returns True when regeneration is required
 */
export function isReadmeOutputStale(existingContent: string | null, options: IDocGenOptions): boolean {
   if (!existingContent) return true;
   const match = README_DATESTAMP_RE.exec(existingContent);
   if (!match) return true;
   const headerDate = parseDateYYYYMMDD(match[1]);
   if (!headerDate) return true;
   const ageMs       = options.jobStartedAt.getTime() - headerDate.getTime();
   const thresholdMs = TIME_WINDOW_DAYS[options.timeWindow] * MS_PER_DAY;
   return ageMs > thresholdMs;
}

/**
 * Builds the datestamp prefix written to the top of generated README files.
 * @param jobStartedAt - Job start timestamp
 * @returns Datestamp line with trailing blank line
 */
export function buildReadmeDatestamp(jobStartedAt: Date): string {
   const dateStr = formatDateYYYYMMDD(jobStartedAt);
   return `${README_DATESTAMP_PREFIX}${dateStr}${README_DATESTAMP_SUFFIX}\n\n`;
}

/**
 * Parses the generated date from a README.StrongAI.*.md file, if present.
 * @param content - README markdown content
 * @returns Parsed generation date or null
 */
export function extractReadmeGeneratedDate(content: string): Date | null {
   const match = README_DATESTAMP_RE.exec(content);
   if (!match) return null;
   return parseDateYYYYMMDD(match[1]);
}

/**
 * Returns true when a rolled-up root README should be regenerated.
 * @param existingRootReadme - Current root rollup content, if any
 * @param childReadmeContents - Subdirectory README inputs for this diagram type
 * @param rootModuleHeaderDates - Dates parsed from root-level module header sentinels
 * @param options - Doc-gen options including jobStartedAt and timeWindow
 * @returns True when rollup output should be rewritten
 */
export function isRollupOutputStale(
   existingRootReadme: string | null,
   childReadmeContents: string[],
   rootModuleHeaderDates: Date[],
   options: IDocGenOptions
): boolean {
   if (isReadmeOutputStale(existingRootReadme, options)) {
      return true;
   }

   const rootRollupDate = extractReadmeGeneratedDate(existingRootReadme!);
   if (!rootRollupDate) {
      return true;
   }

   for (const childContent of childReadmeContents) {
      const childDate = extractReadmeGeneratedDate(childContent);
      if (childDate && childDate.getTime() >= rootRollupDate.getTime()) {
         return true;
      }
   }

   for (const headerDate of rootModuleHeaderDates) {
      if (headerDate.getTime() >= rootRollupDate.getTime()) {
         return true;
      }
   }

   return false;
}
